-- The Black Crowes
INSERT INTO album (album_name, album_release_year) VALUES ('Shake Your Money Maker', '1990');
INSERT INTO album (album_name, album_release_year) VALUES ('The Southern Harmony & Musical Companion', '1992');
INSERT INTO album (album_name, album_release_year) VALUES ('Amorica', '1994');
INSERT INTO album (album_name, album_release_year) VALUES ('Three Snakes And One Charm', '1996');
INSERT INTO album (album_name, album_release_year) VALUES ('By Your Side', '1999');
INSERT INTO album (album_name, album_release_year) VALUES ('Lions', '2001');
INSERT INTO album (album_name, album_release_year) VALUES ('Croweology', '2010');

-- Great White
INSERT INTO album (album_name, album_release_year) VALUES ('Shot In The Dark', '1986');
INSERT INTO album (album_name, album_release_year) VALUES ('Once Bitten...', '1987');
INSERT INTO album (album_name, album_release_year) VALUES ('... Twice Shy', '1989');
INSERT INTO album (album_name, album_release_year) VALUES ('Hooked', '1991');
INSERT INTO album (album_name, album_release_year) VALUES ('Psycho City', '1992');
INSERT INTO album (album_name, album_release_year) VALUES ('Best of Great White', '1993');

-- Motley Crue
INSERT INTO album (album_name, album_release_year) VALUES ('Too Fast For Love', '1981');
INSERT INTO album (album_name, album_release_year) VALUES ('Shout At The Devil', '1983');
INSERT INTO album (album_name, album_release_year) VALUES ('Theatre of Pain', '1985');
INSERT INTO album (album_name, album_release_year) VALUES ('Girls, Girls, Girls', '1987');
INSERT INTO album (album_name, album_release_year) VALUES ('Dr. Feelgood', '1989');
INSERT INTO album (album_name, album_release_year) VALUES ('Decade of Decadence', '1991');

-- Poison
INSERT INTO album (album_name, album_release_year) VALUES ('Look What The Cat Dragged In', '1986');
INSERT INTO album (album_name, album_release_year) VALUES ('Open Up And Say Ahh', '1988');
INSERT INTO album (album_name, album_release_year) VALUES ('Flesh & Blood', '1990');
INSERT INTO album (album_name, album_release_year) VALUES ('Swallow This Live', '1991');

-- The Black Crowes songs
INSERT INTO song (artist_id, song_name) VALUES (1, 'Twice As Hard');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Jealous Again');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Sister Luck');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Could I\'ve Been So Blind');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Seeing Things');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Hard to Handle');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Thick n\' Thin');
INSERT INTO song (artist_id, song_name) VALUES (1, 'She Talks To Angels');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Struttin\' Blues');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Stare It Cold');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Sting Me');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Remedy');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Thorn In My Pride');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Bad Luck Blue Eyes Goodbye');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Sometimes Salvation');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Hotel Illness');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Black Moon Creeping');
INSERT INTO song (artist_id, song_name) VALUES (1, 'No Speak No Slave');
INSERT INTO song (artist_id, song_name) VALUES (1, 'My Morning Song');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Time Will Tell');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Gone');
INSERT INTO song (artist_id, song_name) VALUES (1, 'A Conspiracy');
INSERT INTO song (artist_id, song_name) VALUES (1, 'High Head Blues');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Cursed Diamond');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Nonfiction');
INSERT INTO song (artist_id, song_name) VALUES (1, 'She Gave Good Sunflower');
INSERT INTO song (artist_id, song_name) VALUES (1, 'P. 25 London');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Ballad In Urgency');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Wiser Time');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Downtown Money Waster');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Descending');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Under A Mountain');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Good Friday');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Nebakanezer');
INSERT INTO song (artist_id, song_name) VALUES (1, 'One Mirror Too Many');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Blackberry');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Girl From A Pawnshop');
INSERT INTO song (artist_id, song_name) VALUES (1, '(Only) Halfway To Everywhere');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Bring On, Bring On');
INSERT INTO song (artist_id, song_name) VALUES (1, 'How Much For Your Wings?');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Let Me Share The Ride');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Better When You\'re Not Alone');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Evil Eye');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Go Faster');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Kickin\' My Heart Around');
INSERT INTO song (artist_id, song_name) VALUES (1, 'By Your Side');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Horsehead');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Only A Fool');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Heavy');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Welcome To The Goodtimes');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Go Tell The Congregation');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Diamond Ring');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Then She Said My Name');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Virtue And Vice');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Midnight From The Inside Out');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Lickin\'');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Come On');
INSERT INTO song (artist_id, song_name) VALUES (1, 'No Use Lying');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Losing My Mind');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Ozone Mama');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Greasy Grass River');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Soul Singing');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Miracle To Me');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Young Man, Old Man');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Cosmic Friend');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Cypress Tree');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Lay It All On Me');
INSERT INTO song (artist_id, song_name) VALUES (1, 'Cold Boy Smile');
INSERT INTO song (artist_id, song_name) VALUES (1, 'She');

-- Great White songs
INSERT INTO song (artist_id, song_name) VALUES (2, 'She Shakes Me');
INSERT INTO song (artist_id, song_name) VALUES (2, 'What Do You Do');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Face The Day');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Gimme Some Lovin\'');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Shot In The Dark');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Is Anybody There');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Run Away');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Waiting For Love');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Lady Red Light');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Gonna Getcha');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Rock Me');
INSERT INTO song (artist_id, song_name) VALUES (2, 'All Over Now');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Mistreater');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Never Change Heart');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Fast Road');
INSERT INTO song (artist_id, song_name) VALUES (2, 'On The Edge');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Save Your Love');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Move It');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Heart The Hunter');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Hiway Nights');
INSERT INTO song (artist_id, song_name) VALUES (2, 'The Angel Song');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Mista Bone');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Baby\'s On Fire');
INSERT INTO song (artist_id, song_name) VALUES (2, 'House Of Broken Love');
INSERT INTO song (artist_id, song_name) VALUES (2, 'She Only');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Once Bitten, Twice Shy');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Call It Rock \'n\' Roll');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Original Queen Of Sheba');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Cold Hearted Lovin\'');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Can\'t Shake It');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Lovin\' Kind');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Heartbreaker');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Congo Square');
INSERT INTO song (artist_id, song_name) VALUES (2, 'South Bay Cities');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Desert Moon');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Afterglow');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Psycho City');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Step On You');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Old Rose Motel');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Maybe Someday');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Big Goodbye');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Doctor Me');
INSERT INTO song (artist_id, song_name) VALUES (2, 'I Want You');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Never Trust A Pretty Face');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Love Is A Lie');
INSERT INTO song (artist_id, song_name) VALUES (2, 'Get On Home');

-- Motley Crue songs
INSERT INTO song (artist_id, song_name) VALUES (3, "Live Wire");
INSERT INTO song (artist_id, song_name) VALUES (3, "Public Enemy #1");
INSERT INTO song (artist_id, song_name) VALUES (3, "Take Me to the Top");
INSERT INTO song (artist_id, song_name) VALUES (3, "Merry-Go-Round");
INSERT INTO song (artist_id, song_name) VALUES (3, "Piece of Your Action");
INSERT INTO song (artist_id, song_name) VALUES (3, "Starry Eyes");
INSERT INTO song (artist_id, song_name) VALUES (3, "Stick to Your Guns");
INSERT INTO song (artist_id, song_name) VALUES (3, "Come On and Dance");
INSERT INTO song (artist_id, song_name) VALUES (3, "Too Fast for Love");
INSERT INTO song (artist_id, song_name) VALUES (3, "On with the Show");
INSERT INTO song (artist_id, song_name) VALUES (3, "In the Beginning");
INSERT INTO song (artist_id, song_name) VALUES (3, "Shout at the Devil");
INSERT INTO song (artist_id, song_name) VALUES (3, "Looks That Kill");
INSERT INTO song (artist_id, song_name) VALUES (3, "Bastard");
INSERT INTO song (artist_id, song_name) VALUES (3, "God Bless the Children of the Beast");
INSERT INTO song (artist_id, song_name) VALUES (3, "Helter Skelter");
INSERT INTO song (artist_id, song_name) VALUES (3, "Red Hot");
INSERT INTO song (artist_id, song_name) VALUES (3, "Too Young to Fall in Love");
INSERT INTO song (artist_id, song_name) VALUES (3, "Knock 'Em Dead, Kid");
INSERT INTO song (artist_id, song_name) VALUES (3, "Ten Seconds to Love");
INSERT INTO song (artist_id, song_name) VALUES (3, "Danger");
INSERT INTO song (artist_id, song_name) VALUES (3, "City Boy Blues");
INSERT INTO song (artist_id, song_name) VALUES (3, "Smokin' In The Boys Room");
INSERT INTO song (artist_id, song_name) VALUES (3, "Louder Than Hell");
INSERT INTO song (artist_id, song_name) VALUES (3, "Keep Your Eye On The Money");
INSERT INTO song (artist_id, song_name) VALUES (3, "Home Sweet Home");
INSERT INTO song (artist_id, song_name) VALUES (3, "Tonight (We Need a Lover)");
INSERT INTO song (artist_id, song_name) VALUES (3, "Use It or Lose It");
INSERT INTO song (artist_id, song_name) VALUES (3, "Save Our Souls");
INSERT INTO song (artist_id, song_name) VALUES (3, "Raise Your Hands To Rock");
INSERT INTO song (artist_id, song_name) VALUES (3, "Fight For Your Rights");
INSERT INTO song (artist_id, song_name) VALUES (3, "Wild Side");
INSERT INTO song (artist_id, song_name) VALUES (3, "Girls, Girls, Girls");
INSERT INTO song (artist_id, song_name) VALUES (3, "Dancing On Glass");
INSERT INTO song (artist_id, song_name) VALUES (3, "Bad Boy Boogie");
INSERT INTO song (artist_id, song_name) VALUES (3, "Nona");
INSERT INTO song (artist_id, song_name) VALUES (3, "Five Years Dead");
INSERT INTO song (artist_id, song_name) VALUES (3, "All in the Name Of...");
INSERT INTO song (artist_id, song_name) VALUES (3, "Sumthin' for Nuthin\'");
INSERT INTO song (artist_id, song_name) VALUES (3, "You\'re All I Need");
INSERT INTO song (artist_id, song_name) VALUES (3, "Dr. Feelgood");
INSERT INTO song (artist_id, song_name) VALUES (3, "Slice of Your Pie");
INSERT INTO song (artist_id, song_name) VALUES (3, "Rattlesnake Shake");
INSERT INTO song (artist_id, song_name) VALUES (3, "Kickstart My Heart");
INSERT INTO song (artist_id, song_name) VALUES (3, "Without You");
INSERT INTO song (artist_id, song_name) VALUES (3, "Same Ol' Situation (S.O.S.)");
INSERT INTO song (artist_id, song_name) VALUES (3, "Sticky Sweet");
INSERT INTO song (artist_id, song_name) VALUES (3, "She Goes Down");
INSERT INTO song (artist_id, song_name) VALUES (3, "Don\'t Go Away Mad (Just Go Away)");
INSERT INTO song (artist_id, song_name) VALUES (3, "Time for Change");

-- Poison songs
INSERT INTO song (artist_id, song_name) VALUES (4, 'Cry Tough');
INSERT INTO song (artist_id, song_name) VALUES (4, 'I Won\'t Forget You');
INSERT INTO song (artist_id, song_name) VALUES (4, 'Play Dirty');
INSERT INTO song (artist_id, song_name) VALUES (4, 'Want Some, Need Some');
INSERT INTO song (artist_id, song_name) VALUES (4, 'Blame It On You');
INSERT INTO song (artist_id, song_name) VALUES (4, '#1 Bad Boy');
INSERT INTO song (artist_id, song_name) VALUES (4, 'Let Me Go to the Show');
INSERT INTO song (artist_id, song_name) VALUES (4, 'Back To The Rocking Horse');
INSERT INTO song (artist_id, song_name) VALUES (4, 'Tearin\' Down The Walls');
INSERT INTO song (artist_id, song_name) VALUES (4, 'Bad To Be Good');
INSERT INTO song (artist_id, song_name) VALUES (4, 'Valley of Lost Souls');
INSERT INTO song (artist_id, song_name) VALUES (4, '(Flesh & Blood) Sacrifice');
INSERT INTO song (artist_id, song_name) VALUES (4, 'Come Hell or High Water');
INSERT INTO song (artist_id, song_name) VALUES (4, 'Don\'t Give Up an Inch');
INSERT INTO song (artist_id, song_name) VALUES (4, 'Ball and Chain');
INSERT INTO song (artist_id, song_name) VALUES (4, 'Life Loves a Tragedy');
INSERT INTO song (artist_id, song_name) VALUES (4, 'Look What the Cat Dragged In');
INSERT INTO song (artist_id, song_name) VALUES (4, 'Look But You Can\'t Touch');
INSERT INTO song (artist_id, song_name) VALUES (4, 'Let It Play');
INSERT INTO song (artist_id, song_name) VALUES (4, 'Good Love');
INSERT INTO song (artist_id, song_name) VALUES (4, 'Life Goes On');
INSERT INTO song (artist_id, song_name) VALUES (4, 'Ride the Wind');
INSERT INTO song (artist_id, song_name) VALUES (4, 'I Want Action');
INSERT INTO song (artist_id, song_name) VALUES (4, 'Something To Believe In');
INSERT INTO song (artist_id, song_name) VALUES (4, 'Poor Boy Blues');
INSERT INTO song (artist_id, song_name) VALUES (4, 'Unskinny Bop');
INSERT INTO song (artist_id, song_name) VALUES (4, 'Love on the Rocks');
INSERT INTO song (artist_id, song_name) VALUES (4, 'Every Rose Has Its Thorn');
INSERT INTO song (artist_id, song_name) VALUES (4, 'Fallen Angel');
INSERT INTO song (artist_id, song_name) VALUES (4, 'Your Mama Don\'t Dance');
INSERT INTO song (artist_id, song_name) VALUES (4, 'Nothin\' But a Good Time');
INSERT INTO song (artist_id, song_name) VALUES (4, 'Talk Dirty to Me');